<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,3,1,'6L276Z+z5LmQ');
$cfg_Cs[2]=array(1,3,1,'6ZKi55C05puy');
$cfg_Cs[3]=array(0,3,1,'5rWB6KGM');
$cfg_Cs[4]=array(0,1,0,'5Zyo57q/55WZ6KiA');
$cfg_Cs[6]=array(0,3,0,'6Z+z5LmQ5LiT6L6R');
$cfg_Cs[7]=array(1,3,1,'5ZCJ5LuW5puy');
$cfg_Cs[8]=array(0,3,1,'TVY=');
$cfg_Cs[9]=array(3,3,1,'5Y2O6K+t5rWB6KGM');
$cfg_Cs[10]=array(3,3,1,'5pGH5rua6K+05ZSx');
$cfg_Cs[11]=array(3,3,1,'5aSW6K+t57uP5YW4');
$cfg_Cs[12]=array(3,3,1,'5qCh5Zut57uP5YW4');
$cfg_Cs[13]=array(3,3,1,'REroiJ7mm7I=');
?>