<li class="boxgrid caption">
				<img src="[field:litpic/]" alt="" />
				<div class="cover boxcaption">
					<h3>[field:title/]</h3>
					<p class="icon_play"  onmouseover="this.className='icon_play icon_play_hover'" onmouseout="this.className='icon_play'">
					演奏/演唱：[field:writer/]<br/>类型：[field:typename/]<br/>播放[field:click /]次
					<a href="[field:arcurl/]" target="_blank" title="立即播放"><span> </span></a></p>
				</div>
			</li>