<?php
$z[0]=Array("field","",47,75);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",77,106);
$z[1][4]['name']="typename";
$z[2]=Array("field","",379,407);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n      <li class=\"show_data\" onmouseover=\"this.className='show_play'\" onmouseout=\"this.className='show_data'\">\r\n	  <input type=\"checkbox\" name=\"jtbox\" value=\"[field:id /]\" class=\"play_checkbox\"/>\r\n	  <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n	  <div class=\"list_cp\" >\r\n		<span class=\"data\">[field:pubdate function=MyDate('m-d',@me)/]</span>\r\n			<a href=\"[field:arcurl/]\"  class=\"btn_play\" title=\"播放\" target=\"_blank\">播放</a>\r\n			<!--a href=\"\" class=\"btn_add\" title=\"添加\"  target=\"_blank\">添加</a-->\r\n			<a class=\"btn_add\" href=\"/plus/stow.php?aid=[field:id/]&music_url=[field:music_url/]&type=3\" title=\"加入我的播放列表\" target=\"_blank\"></a>\r\n			<a href=\"/plus/recommend.php?aid=[field:id/]\" title=\"推荐给好友\" class=\"btn_tuijian\" target=\"_blank\">推荐</a>\r\n         </div>\r\n	  </li>\r\n      ",479,1389);
$z[3][4]['addfields']="music_url";
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";
$z[3][4]['channelid']="3";

?>