<?php
$z[0]=Array("id","",156,168);
$z[1]=Array("arcurl","",190,205);
$z[2]=Array("title","",237,251);
$z[3]=Array("pubdate","",342,388);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("softrank","",420,465);
$z[4][4]['function']="GetRankStar(@me)";
$z[5]=Array("click","",497,511);
$z[6]=Array("arcurl","",543,558);
$z[7]=Array("id","",671,682);
$z[8]=Array("music_url","",693,711);
$z[9]=Array("id","",816,827);

?>