<?php
$z[0]=Array("id","",153,165);
$z[1]=Array("arcurl","",185,200);
$z[2]=Array("title","",232,246);
$z[3]=Array("pubdate","",337,383);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("softrank","",415,460);
$z[4][4]['function']="GetRankStar(@me)";
$z[5]=Array("click","",492,506);
$z[6]=Array("arcurl","",538,553);
$z[7]=Array("id","",666,677);
$z[8]=Array("music_url","",688,706);
$z[9]=Array("id","",811,822);

?>