{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist='44,43,41,40,3942'
                name='收录歌曲' noteid='default' isauto='0' rownum='10'
                keywords='' typeid='0'}
                <li><input type="checkbox" name="jtbox" value="[field:id /]" class="play_checkbox" style="float: left;margin: 5px 5px;"/><span class="date">[field:typename/]</span><a href="[field:arcurl /]" target="_blank">[field:title /]</a></li>
                {/dede:specnote}
