<?php
$z[0]=Array("spaceurl","",93,111);
$z[1]=Array("face","",156,169);
$z[2]=Array("spaceurl","",217,235);
$z[3]=Array("uname","",270,284);
$z[4]=Array("spaceurl","",336,354);
$z[5]=Array("spaceurl","",431,449);
$z[6]=Array("spaceurl","",537,555);
$z[7]=Array("rankname","",702,720);
$z[8]=Array("jointime","",789,841);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",910,963);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>