<?php
$z[0]=Array("id","",74,85);
$z[1]=Array("title","",106,120);
$z[2]=Array("music_url","",140,158);
$z[3]=Array("litpic","",180,196);
$z[4]=Array("title","",484,499);
$z[5]=Array("litpic","",533,548);
$z[6]=Array("title","",580,595);
$z[7]=Array("id","",660,672);
$z[8]=Array("id","",757,769);
$z[9]=Array("title","",916,931);
$z[10]=Array("title","",957,972);
$z[11]=Array("writer","",1013,1028);
$z[12]=Array("typename","",1042,1059);
$z[13]=Array("click","",1070,1085);

?>