<?php
$z[0]=Array("specnote","\r\n                <li><input type=\"checkbox\" name=\"jtbox\" value=\"[field:id /]\" class=\"play_checkbox\" style=\"float: left;margin: 5px 5px;\"/><span class=\"date\">[field:typename/]</span><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n                ",0,517);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="5,4,3,2,1";
$z[0][4]['name']="收录歌曲";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="10";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>