<?php
$z[0]=Array("id","",51,62);
$z[1]=Array("title","",83,97);
$z[2]=Array("music_url","",117,135);
$z[3]=Array("litpic","",157,173);
$z[4]=Array("title","",461,476);
$z[5]=Array("litpic","",510,525);
$z[6]=Array("title","",557,572);
$z[7]=Array("id","",637,649);
$z[8]=Array("id","",734,746);
$z[9]=Array("title","",893,908);
$z[10]=Array("title","",934,949);
$z[11]=Array("title","",981,996);
$z[12]=Array("title","",998,1013);

?>