<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><!-- //底部模板 -->
<div class="footer w960 center mt1 clear">
    <div class="footer_left"></div>
    <div class="footer_body">
	    <span style="position:fixed; right:15px; bottom:25px;"><a href="javascript:scroll(0,0)"><img src="/images/top.gif" alt="返回顶部" title="返回顶部"/></a></span>
	    
		<div class="copyright"><?php echo $GLOBALS['cfg_powerby']; ?>  <?php echo $GLOBALS['cfg_beian']; ?> </div>      
<!-- /powered -->
   </div>
   <div class="footer_right"></div>
   <p class="w3c">
    <a href="http://validator.w3.org/check?uri=referer" target="_blank">
	<img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" />
	</a>
	 <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">
        <img style="border:0;" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" />
    </a>
	<a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">
    <img style="border:0;" src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" />
	</a>
  </p>
   <div class="tongji" style="margin:auto" align="center">
   <script src="http://s84.cnzz.com/stat.php?id=3483221&web_id=3483221&show=pic" language="JavaScript" type="text/javascript"></script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fbd8e9c876f8adaf70538c0492cafdcd6' type='text/javascript'%3E%3C/script%3E"));
</script>

	</div>
</div>